force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>IB-{0000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Book_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Book_Quantity__c</fullName>
    <label>Book Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_Borrowed__c/Item_Borrowed__c.object-meta.xml
<CustomObject>
    <label>Item Borrowed</label>
    <nameField>
        <displayFormat>IB-{0000}</displayFormat>
        <label>Items Borrowed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items Borrowed</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Borrowed__c/fields/Book_Status__c.field-meta.xml
<CustomField>
    <fullName>Book_Status__c</fullName>
    <label>Book Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_Borrowed__c/fields/Item_Borrowed_Field__c.field-meta.xml
<CustomField>
    <fullName>Item_Borrowed_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Borrowed_Field</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Items Borrowed (Item Borrowed)</relationshipLabel>
    <relationshipName>Items_Borrowed1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ItemBorrowedQuantityHelper.cls
public class ItemBorrowedQuantityHelper {
    
    List<Item_Borrowed__c> itemBorrowedList;
    Map<Id, Item_Borrowed__c> oldItemBorrowedMap;
    
    public ItemBorrowedQuantityHelper(List<Item_Borrowed__c> itemBorrowedList, Map<Id, Item_Borrowed__c> oldItemBorrowedMap)
    {
        this.itemBorrowedList = itemBorrowedList;
        this.oldItemBorrowedMap = oldItemBorrowedMap;
    }
    
    public ItemBorrowedQuantityHelper reduceQuantityOfBookOnIssuance()
    {
        
        List<Book__c> bookToUpdate = new List<Book__c>();
        Set<Id> bookIds =new Set<Id>();
        
        Map<Id, Integer> bookMap = new Map<Id, Integer>();
        
        for(Item_Borrowed__c itemBorrowed : itemBorrowedList)
        {
            if(itemBorrowed.Book_Status__c == 'Issued' && oldItemBorrowedMap.get(itemBorrowed.Id).Book_Status__c != 'Issued')
            {
				bookIds.add(itemBorrowed.Item_Borrowed_Field__c);
            }
        }
        
        System.debug('The bookd ids is : ' + bookIds);
        
        Map<Id, Book__c> bookWithQuantityMap = new Map<Id, Book__c>([
            SELECT Id, Book_Quantity__c FROM Book__c WHERE Id IN : bookIds
        ]);
        
        System.debug('The bookWithQuantityMap is : ' + bookWithQuantityMap);
        
        for(Item_Borrowed__c itemBorrowed: itemBorrowedList)
        {
            if(itemBorrowed.Book_Status__c == 'Issued' && oldItemBorrowedMap.get(itemBorrowed.Id).Book_Status__c != 'Issued'){
				
                if(bookMap.containsKey(itemBorrowed.Item_Borrowed_Field__c)){
                    Integer count = bookMap.get(itemBorrowed.Item_Borrowed_Field__c);
                    bookMap.put(itemBorrowed.Item_Borrowed_Field__c, count - 1);
                }
                else{
                    	bookMap.put(itemBorrowed.Item_Borrowed_Field__c, (Integer)(bookWithQuantityMap.get(itemBorrowed.Item_Borrowed_Field__c).Book_Quantity__c -1));
					}
        	}  
  		}
        
        System.debug('The bookMap is : ' + bookMap);
        
        if(bookMap.size() > 0){
            for(Id bookId : bookMap.keySet()){
				   bookToUpdate.add(new Book__c(
                   		Id = bookId,
                   		Book_Quantity__c = bookMap.get(bookId)
                   ));
            	}
        }
        
        System.debug('The bookToUpdate is : ' + bookToUpdate);
        
        if(bookToUpdate.size()> 0 )
        {
			update bookToUpdate;     
 	   }
        
        return this;
	}
    
     public ItemBorrowedQuantityHelper increaseQuantityOfBookOnReturn()
    {
        
        List<Book__c> bookToUpdate = new List<Book__c>();
        Set<Id> bookIds =new Set<Id>();
        
        Map<Id, Integer> bookMap = new Map<Id, Integer>();
        
        for(Item_Borrowed__c itemBorrowed : itemBorrowedList)
        {
            if(itemBorrowed.Book_Status__c == 'Returned' && oldItemBorrowedMap.get(itemBorrowed.Id).Book_Status__c != 'Returned'){
				bookIds.add(itemBorrowed.Item_Borrowed_Field__c);
            }
        }
        
        System.debug('The bookd ids is : ' + bookIds);
        
        Map<Id, Book__c> bookWithQuantityMap = new Map<Id, Book__c>([
            SELECT Id, Book_Quantity__c FROM Book__c WHERE Id IN : bookIds
        ]);
        
        
        for(Item_Borrowed__c itemBorrowed: itemBorrowedList){
            if(itemBorrowed.Book_Status__c == 'Returned' && oldItemBorrowedMap.get(itemBorrowed.Id).Book_Status__c != 'Returned'){
				
                if(bookMap.containsKey(itemBorrowed.Item_Borrowed_Field__c)){
                    Integer count = bookMap.get(itemBorrowed.Item_Borrowed_Field__c);
                    bookMap.put(itemBorrowed.Item_Borrowed_Field__c, count + 1);
                }
                else{
                    	bookMap.put(itemBorrowed.Item_Borrowed_Field__c, (Integer)(bookWithQuantityMap.get(itemBorrowed.Item_Borrowed_Field__c).Book_Quantity__c +1));
					}
        	}  
  		}
        
        System.debug('The bookMap is : ' + bookMap);
        
        if(bookMap.size() > 0)
        {
            for(Id bookId : bookMap.keySet()){
				   bookToUpdate.add(new Book__c(
                   		Id = bookId,
                   		Book_Quantity__c = bookMap.get(bookId)
                   ));
            	}
        }
        
        System.debug('The bookToUpdate is : ' + bookToUpdate);
        
        if(bookToUpdate.size()>= 0 )
         {
			update bookToUpdate;     
 	  	 }
        
        return this;
	}
}