force-app/main/default/objects/Item_Borrowed__c/Item_Borrowed__c.object-meta.xml
<CustomObject>
    <label>Item Borrowed</label>
    <nameField>
        <displayFormat>IB-{0000}</displayFormat>
        <label>Items Borrowed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items Borrowed</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Borrowed__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <formula>Borrowed_Date__c + 30</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Item_Borrowed__c/fields/Fine_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fine_Amount__c</fullName>
    <label>Fine Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FineCalculateBatchClass.cls
global class FineCalculateBatchClass implements Database.Batchable<sObject> , Schedulable
{
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
		String query = 'SELECT Id, Due_Date__c FROM Item_Borrowed__c WHERE Due_Date__c < TODAY';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Item_Borrowed__c> lList)
    {
		for(Item_Borrowed__c IB : lList)
        {
			Integer daysLate = IB.Due_Date__c.daysBetween(Date.today());
            
            Integer fineAmount = daysLate * 5 ;
            
            IB.Fine_Amount__c = fineAmount;
        }
        
        update lList;
    }
    
    global void finish(Database.BatchableContext bc)
    { 
        
    }
    
    global void execute(SchedulableContext sc)
	{
    FineCalculateBatchClass batchJob = new FineCalculateBatchClass();
    Database.executeBatch(batchJob);
	}
    
}